name: Build

env:
  GITHUB_PUBLISH: 'false'

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths-ignore:
      - LICENSE
      - README.md
      - 'docs/**'
      - '.github/config/labels.yml'

  pull_request:
    branches:
      - main

  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Gradle Build
    timeout-minutes: 15
    continue-on-error: false
    # if: github.event_name  == 'pull_request'

    outputs:
      version: ${{ steps.gradle-build.outputs.version }}
      artifact_name: ${{ steps.gradle-build.outputs.uberjar_name }}

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        jdk: [ Loom ]
        include:
          - os: ubuntu-latest
            cmd: ./gradlew
          - os: macos-latest
            cmd: ./gradlew
          - os: windows-latest
            cmd: ./gradlew.bat

    steps:
      - name: Check out the source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Download ${{ matrix.os }} OpenJDK ${{ matrix.jdk }}
        id: download-jdk
        uses: sormuras/download-jdk@v1
        with:
          feature: ${{ matrix.jdk }}

      - name: Set up OpenJDK ${{ matrix.jdk }}
        id: setup-java
        uses: actions/setup-java@v2
        if: always() && steps.download-jdk.outcome == 'success'
        with:
          distribution: jdkfile
          java-version: ${{ env.JDK_VERSION }}
          jdkFile: ${{ env.JDK_FILE }}

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Publish to GitHub Packages (Linux)
        id: gradle-publish
        if: env.GITHUB_PUBLISH == 'true' && runner.os == 'Linux'
        run: |
          ./gradlew publish
        env:
          GITHUB_USER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Gradle Run & Build
        id: gradle-build
        run: ./gradlew clean run build

      - name: Uploading ${{ matrix.os }} uber jar
        if: steps.gradle-build.outcome == 'success' && runner.os == 'Linux'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.gradle-build.outputs.uberjar_name }}
          path: |
            ${{ steps.gradle-build.outputs.uberjar_path }}
          if-no-files-found: error

  release:
    name: Release new version.
    needs: [ build ]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Check out the source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1.8.2
        with:
          configuration: ".github/config/configuration.json"
          commitMode: true
          ignorePreReleases: ${{ !contains(github.ref, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download all the build artifacts
        uses: actions/download-artifact@v2
        with:
          path: release-artifacts

      - name: Github Release (version = ${{ needs.build.outputs.version }})
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.github_release.outputs.changelog }}
          prerelease: ${{ contains(github.event.inputs.version, '-rc') || contains(github.event.inputs.version, '-b') || contains(github.event.inputs.version, '-a') }}
          files: |
            ${{ github.workspace }}/release-artifacts/**
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}